// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCFOR10Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\gaeta\\Desktop\\Cartelle\\UNISA\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCFOR101() {
    driver.get("http://localhost:8080/EasyExpo_war/login.jsp");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".icon-user")).click();
    driver.findElement(By.linkText("RICHIESTE")).click();
    driver.findElement(By.linkText("READ MORE")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("1000.00");
    driver.findElement(By.name("nota")).click();
    driver.findElement(By.name("nota")).sendKeys("Gregorio Samsa, svegliandosi una mattina da sogni agitati, si trovò trasformato, nel suo letto, in un enorme insetto immondo. Riposava sulla schiena, dura come una corazza, e sollevando un poco il capo vedeva il suo ventre arcuato, bruno e diviso");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCFOR102() {
    driver.get("http://localhost:8080/EasyExpo_war/login.jsp");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".icon-user")).click();
    driver.findElement(By.linkText("RICHIESTE")).click();
    driver.findElement(By.linkText("READ MORE")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("1000.00");
    driver.findElement(By.name("nota")).click();
    driver.findElement(By.name("nota")).sendKeys("Casse **");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCFOR103() {
    driver.get("http://localhost:8080/EasyExpo_war/login.jsp");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".icon-user")).click();
    driver.findElement(By.linkText("RICHIESTE")).click();
    driver.findElement(By.linkText("READ MORE")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("855556,000");
    driver.findElement(By.name("nota")).click();
    driver.findElement(By.name("nota")).sendKeys("Casse musicali disponibili con uno sconto");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCFOR104() {
    driver.get("http://localhost:8080/EasyExpo_war/login.jsp");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".icon-user")).click();
    driver.findElement(By.linkText("RICHIESTE")).click();
    driver.findElement(By.linkText("READ MORE")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("prezzo")).click();
    driver.findElement(By.name("prezzo")).sendKeys("1000.00");
    driver.findElement(By.name("nota")).click();
    driver.findElement(By.name("nota")).sendKeys("Casse musicali disponibili con uno sconto");
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
