// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCGACC1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\gaeta\\Desktop\\Cartelle\\UNISA\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCGACC11() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Ezio.g@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC12() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Ezio.g@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC13() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio_1");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Ezio.g@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC14() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Ezio.g@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC15() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Ezio.g@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC16() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio01");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Ezio.g@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC17() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("@gmail.it");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC18() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura ché la diritta via era smarrita. Ahi quanto a dir qual era è cosa dura esta selva selvaggia");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC19() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("Eziogreggiogmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC110() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("gaetano99@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC111() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC112() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E91@#");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC113() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abc123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC114() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC115() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC116() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("abcdef1");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC117() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdef345");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC118() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC119() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC120() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("5454545");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC121() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("33782");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC122() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("33782ciao");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACC123() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneCliente.jsp");
    driver.manage().window().setSize(new Dimension(1580, 805));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Ezio");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Greggio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("e.greggio@gmail.com");
    driver.findElement(By.cssSelector(".col-md-6:nth-child(4)")).click();
    driver.findElement(By.name("password")).sendKeys("Abcdefg123");
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("Abcdefg123");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3378256957");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.name("codiceFiscale")).click();
    driver.findElement(By.name("codiceFiscale")).sendKeys("EZIMNC89D44E919D");
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
