// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TCGACF1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\gaeta\\Desktop\\Cartelle\\UNISA\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tCGACF11() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF12() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Nelmezzodelcammindinostravita miritrovaiperunaselvaoscura\\nchélairittaiaerasmarritaAhquantodirqual eracosadura\\nestaselvaselvaggia\\n");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF13() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario123");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF14() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF15() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Nelmezzodelcammindinostravita miritrovaiperunaselvaoscura\\nchélairittaiaerasmarritaAhquantodirqual eracosadura\\nestaselvaselvaggia\\n");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF16() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi123");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF17() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF18() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234§");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF19() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF110() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234§");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF111() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBbCcDd1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF112() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF113() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("NelmezzodelcammindinostravitamiritrovaiperunaselvaoscurachélairittaiaerasmarritaAhquantodirqualeracosaduraestaselvaselvaggia@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF114() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi§§§@ music&service468.info");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF115() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("zaidane68a@mailstop.it");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF116() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("123456789123456789");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF117() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("33333333LK");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF118() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF119() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("NelmezzodelcammindinostravitamiritrovaiperunaselvaoscurachélairittaiaerasmarritaAhquantodirqualeracosaduraestaselvaselvaggia");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF120() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl?^");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF121() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF122() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("ABCDEF78910");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF123() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF124() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("NelmezzodelcammindinostravitamiritrovaiperunaselvaoscurachélairittaiaerasmarritaAhquantodirqualeracosaduraestaselvaselvaggia");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF125() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma12");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void tCGACF126() {
    driver.get("http://localhost:8080/EasyExpo_war/registrazioneFornitore.jsp");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Mario");
    driver.findElement(By.name("cognome")).click();
    driver.findElement(By.name("cognome")).sendKeys("Rossi");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("AaBb1234");
    driver.findElement(By.cssSelector(".sticky > .container")).click();
    driver.findElement(By.name("passwordConferma")).click();
    driver.findElement(By.name("passwordConferma")).sendKeys("AaBb1234");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mario.rossi@gmail.com");
    driver.findElement(By.name("telefono")).click();
    driver.findElement(By.name("telefono")).sendKeys("3333333333");
    driver.findElement(By.name("ragioneSociale")).click();
    driver.findElement(By.name("ragioneSociale")).sendKeys("Music&Service srl");
    driver.findElement(By.name("partitaIva")).click();
    driver.findElement(By.name("partitaIva")).sendKeys("01234567890");
    driver.findElement(By.name("luogoUbicazione")).click();
    driver.findElement(By.name("luogoUbicazione")).sendKeys("Roma");
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
